### ISSUE TITLE
TP=4 loads all weights on GPU 0 — GPUs 1-3 at 15 MiB, OOM on GPU 0

### ISSUE THREAD

**Issue by ipixeldust** [0xSero/deepseek-v4-flash-sm120#4]
## Hardware

- 4× NVIDIA RTX PRO 6000 Blackwell **Max-Q Workstation Edition** (SM120)
- Driver: 580.159.03 (downgraded from 590.x to match closer to your reference stack)
- CUDA: 13.0
- OS: Ubuntu 24.04, kernel 6.17.0-22-generic
- PCIe topology (from `nvidia-smi topo -m`):

```
        GPU0   GPU1   GPU2   GPU3
GPU0     X     PHB    NODE   NODE
GPU1    PHB     X     NODE   NODE
GPU2    NODE   NODE    X     NODE
GPU3    NODE   NODE   NODE    X
```

GPU0/GPU1 share a PCIe host bridge. GPU2/GPU3 are on separate bridges within the same NUMA node. No NVLink. Bus IDs: 01:00, 02:00, 85:00, C2:00.

## Problem

With TP=4 and any launch configuration, all MoE expert weights load onto GPU 0. GPUs 1-3 remain at ~15 MiB. GPU 0 then OOMs during expert weight allocation:

```
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB.
GPU 0 has a total capacity of 94.97 GiB of which 164.81 MiB is free.
Including non-PyTorch memory, this process has 3.18 GiB memory in use.
```

GPU memory at failure: `GPU 0: 93817 MiB | GPU 1: 15 MiB | GPU 2: 15 MiB | GPU 3: 15 MiB`

Weight distribution is not happening — everything piles on GPU 0.

## What we tried (8 rounds)

**PR #3 kernel path:**
- Built `0xSero/deepseek-v4-flash-sm120` PR #3 kernel locally against driver 580.x
- Applied both canonical hot-patches: `window_size` getattr-chain fix + memory-balance bypass
- Verified both patches load at runtime

**vLLM path (spark-vllm-docker PR #40991):**
- Built `vllm-sm120-v4flash:nccl-stock` (replaced aarch64 NCCL with stock nvidia-nccl-cu13)
- Built `vllm-sm120-v4flash:instanttensor` derivative with instanttensor baked in

**Env vars tried:**
```
NCCL_P2P_DISABLE=1
SAFETENSORS_FAST_GPU=0
SGLANG_DISABLE_DEEP_GEMM=1
DG_JIT_USE_NVRTC=0
VLLM_DISABLED_KERNELS=CutlassFp8BlockScaledMMKernel
VLLM_USE_FLASHINFER_MOE_FP8=1
VLLM_TRITON_MLA_SPARSE=1
```

**Launch flags tried:**
- `--tensor-parallel-size 4`, `--tensor-parallel-size 2`
- `--distributed-executor-backend mp` and `ray`
- `--mem-fraction-static 0.65`
- `--max-running-requests 1`
- `--context-length 16384`
- `--gpus "device=0,1,2,3"` strict
- `--enforce-eager`

**Cleanup between attempts:** `sudo fuser -k -9 /dev/nvidia*` + force-killed all GPU PIDs.

## Working baseline

vLLM path works for single-GPU (TP=1) on GPU 3 — model loads and serves. The weight distribution failure is specific to multi-GPU TP.

## What we suspect

The NODE topology between GPU0/GPU1 and GPU2/GPU3 may be causing NCCL to choose a communication path that breaks weight shard assignment during model load. P2P writes between GPU0↔GPU2 and GPU0↔GPU3 traverse the CPU/memory bus, not direct PCIe. It's possible your working setup has a different PCIe topology or NCCL config that works around this.

## Questions

1. What does `nvidia-smi topo -m` show on your working setup?
2. Are there any NCCL env vars, nvidia module parameters, or BIOS settings (IOMMU, PCIe ACS) that differ from defaults?
3. Is there anything in `/proc/driver/nvidia/params` or modprobe options for the nvidia driver that your setup requires?

Happy to provide any additional logs. Full failure logs at `/mnt/data/logs/dsv4-final-580.log` on our end.

**Comment by ipixeldust** [comment]
## Diagnostic update — IOMMU is the root cause

Collected the four artifacts recommended by community threads on identical hardware (WRX90 + RTX PRO 6000 Blackwell).

### /proc/cmdline
```
BOOT_IMAGE=/vmlinuz-6.17.0-22-generic root=/dev/mapper/ubuntu--vg-ubuntu--lv ro
```
No IOMMU parameters — IOMMU running in default mode (active, not passthrough).

### nvidia-smi topo -p2p p
```
     GPU0  GPU1  GPU2  GPU3
GPU0   X    OK    OK    OK
GPU1  OK     X    OK    OK
GPU2  OK    OK     X    OK
GPU3  OK    OK    OK     X
```
Static P2P capability shows OK for all pairs — consistent with both forum reports where `isAllDirectP2p=1` but actual DMA transfers still fail under IOMMU.

### dmesg — AER errors on GPU0's PCIe port
```
pcieport 0000:00:01.1: aer_status: 0x00000040  ← Replay Timer Timeout (PCIe retries)
nvidia 0000:01:00.0: aer_status: 0x00000001    ← Receiver Error
```
Correctable PCIe errors on the host bridge shared by GPU0/GPU1 (bus 01/02) and on GPU0 itself. This matches the pattern of IOMMU intercepting and rejecting P2P DMA writes, causing PCIe link-level retries.

### Conclusion

The failure pattern — all MoE weights loading on GPU0, GPUs 1-3 at 15 MiB, OOM on GPU0 — is consistent with IOMMU blocking cross-GPU DMA, not a missing kernel or env var. Found two independent threads on identical RTX PRO 6000 Blackwell + WRX90 hardware with the same symptom resolved by IOMMU changes:
- [NVIDIA Dev Forum: NCCL P2P hang on dual RTX PRO 6000 Blackwell WRX90E](https://forums.developer.nvidia.com/t/nccl-p2p-hang-on-dual-rtx-pro-6000-blackwell-workstation-edition-wrx90e-sage-se/365048) — fixed by disabling IOMMU+ACS in BIOS
- [Level1Techs: dual RTX PRO 6000 Blackwell Max-Q P2P/NCCL](https://forum.level1techs.com/t/dual-rtx-pro-6000-blackwell-max-q-how-to-make-p2p-nccl-work/242403) — fixed by `amd_iommu=on iommu=pt` + ACS off in BIOS

We're now applying `amd_iommu=on iommu=pt` via GRUB and rebooting. Will report back with results.

**Questions for you:** What does your `nvidia-smi topo -m` show, and what are your IOMMU/ACS BIOS settings? That would confirm whether topology is the diff between our setups.

**Comment by ipixeldust** [comment]
## Fix confirmed: `iommu=pt` resolves TP=4 weight distribution

After adding `amd_iommu=on iommu=pt` to GRUB and rebooting, TP=4 now distributes weights correctly across all 4 GPUs:

```
GPU 0: 86799 MiB
GPU 1: 86799 MiB  
GPU 2: 86799 MiB
GPU 3: 86799 MiB
```

Previously: GPU 0: 93817 MiB | GPU 1: 15 MiB | GPU 2: 15 MiB | GPU 3: 15 MiB (OOM)

**Root cause:** AMD IOMMU in default mode blocks cross-GPU DMA writes used by NCCL/safetensors during TP weight sharding. Passthrough mode (`iommu=pt`) allows direct GPU-to-GPU P2P DMA.

**Fix:**
```bash
# Edit /etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT="amd_iommu=on iommu=pt"
sudo update-grub && sudo reboot
```

**Diagnostic signals that pointed here:**
- `dmesg | grep AER` showed correctable PCIe errors on GPU0's bridge (`00:01.1`) and GPU0 (`01:00.0`) — signature of blocked P2P DMA causing PCIe retries
- `/proc/cmdline` had no IOMMU params (default = IOMMU active/strict)
- NCCL logs showed `isAllDirectP2p 0` (SHM fallback, not direct P2P)
- Two independent WRX90 + RTX PRO 6000 Blackwell threads confirmed this exact fix

Throughput: ~6.25 tok/s at enforce-eager (MARLIN MoE baseline). Image: `vllm-sm120-v4flash:nccl-stock` via spark-vllm-docker PR #40991.

Hardware: 4× RTX PRO 6000 Blackwell Max-Q Workstation Edition, WRX90, driver 580.159.03, Ubuntu 24.04, kernel 6.17.0-22-generic.
